<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="tests.PostTestCase-20220321233237" tests="12" file="tests.py" time="0.082" timestamp="2022-03-21T23:32:37" failures="2" errors="0" skipped="0">
		<testcase classname="tests.PostTestCase" name="test_task10_uncomment_templates" time="0.037" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="246">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task12_make_migrations" time="0.006" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="282">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task1_tag_model_exists" time="0.007" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="114">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task2_clean_method_exists" time="0.002" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="125">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task3_str_exists" time="0.003" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="132">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task5_tag_view" time="0.003" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="192">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task6_tag_view_title" time="0.003" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="198">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task7_tag_view_find_posts" time="0.003" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="203">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task8_add_tag_url" time="0.001" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="209">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task9_url_reverser" time="0.003" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="236">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task11_admin_register_tag" time="0.010" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="258">
			<failure type="AssertionError" message="Did you import `Tag`?"><![CDATA[Traceback (most recent call last):
  File "C:\Users\santitee\Documents\GitHub\python-django-models-authentication\module4\tests.py", line 279, in test_task11_admin_register_tag
    self.assertTrue(import_Tag_found, msg="Did you import `Tag`?")
  File "C:\Users\santitee\Documents\GitHub\python-django-models-authentication\support\SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you import `Tag`?
]]></failure>
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task4_many_to_many_exists" time="0.004" timestamp="2022-03-21T23:32:37" file="module4\tests.py" line="136">
			<failure type="AssertionError" message="Did you add the `name` field?"><![CDATA[Traceback (most recent call last):
  File "C:\Users\santitee\Documents\GitHub\python-django-models-authentication\module4\tests.py", line 138, in test_task4_many_to_many_exists
    self.assertTrue(self.tags_field_found, msg="Did you add the `name` field?")
  File "C:\Users\santitee\Documents\GitHub\python-django-models-authentication\support\SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you add the `name` field?
]]></failure>
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
	</testsuite>
</testsuites>
